name: Build release
on:
  push:
    branches:
      - "gpi-develop"
jobs:
  build:
    runs-on: [self-hosted, linux, ARM64, rpi]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # fetch git tags for "git describe"
      - name: make
        run: |
          make
